### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by stevenwilkin**
This should push the latest master to rubygems

### CODE REVIEW

**Comment by pirogoeth** [comment]
@stevenwilkin thanks, meant to do this yesterday, but sickness has me a little out of it :flushed:

**Comment by stevenwilkin** [comment]
Champion!

**Comment by stevenwilkin** [comment]
Needs a tag for Travis to push to rubygems I think

**Comment by pirogoeth** [comment]
@stevenwilkin you are correct! I'll get it tagged.

**Pull request merged**
