### PR TITLE
Add Railgun docs, tests, and support ActionMailer headers call

### PR DESCRIPTION
**Pull request by pirogoeth**

### CODE REVIEW

**Comment by holman** [comment]
Haven't tried it in a project yet, but from a cursory glance this looks really great, and just what I was looking for. :+1:

**Comment by derosm2** [comment]
Would love to see this get merged! Definitely killed some time trying to figure out why my headers weren't getting used.

**Comment by rept** [comment]
Would love to see this merged too after spending lots of time trying to get headers included...

**Comment by rept** [comment]
Tested this and works fine.  Tags are coming in nicely in MailGun now.

**Comment by rept** [comment]
Any idea when this could be merged to the master branch?

**Pull request merged**
