### PR TITLE
update rest-client to v2 and drop support for ruby 1.9

### PR DESCRIPTION
**Pull request by manuelmeurer**

### CODE REVIEW

**Comment by zzet** [comment]
@jrodom What do you think about "R.I.P" 1.9.3 ruby support?

**Comment by manuelmeurer** [comment]
Ruby 1.9 has been EOL for 1.5 years now...

**Comment by CGA1123** [comment]
@manuelmeurer Might as well remove `1.9.3` from `.travis.yml`

**Comment by manuelmeurer** [comment]
@CGA1123 True dat!

**Comment by CGA1123** [comment]
Closes #56

**Pull request merged**
