### PR TITLE
Don't force ActionMailer to lazy load before configuration.

### LINKED ISSUE #86: Including 'mailgun-ruby' causes action_mailer configs in an initializer to not be used
Hello, I have encountered an odd scenario where I am unable to set action_mailer configuration options if I include the `mailgun-ruby` gem.

I have a Rails 4.2.7.1 app, where I configure ActionMailer in an initializer. Some of the options I set are the `default_url_options` and `asset_host`, so that images in our emails have an absolute URL rather than a relative one. Without requiring `mailgun-ruby`, emails are generated correctly. As soon as I add `gem 'mailgun-ruby'` to my Gemfile, these options are no longer present at the time the email is rendered. This causes an exception to be throw by Rails stating that the `default_url_options` are not set.

I did some digging, and found that the root cause is the `Railgun::Railtie`, which adds the `mailgun` delivery method in `before_initialize` hook. I can not find any explanation either in Rails or elsewhere that would explain why adding a delivery method would cause subsequent configuration to not be used. I looked at the [Rails initialization events](http://guides.rubyonrails.org/configuring.html#initialization-events) and found nothing that points to a reason why.

I am able to work around this issue by requiring all necessary files except the Railtie. I'm not actually using the `mailgun` delivery method, my use case requires me to manually call `Railgun.transform_for_mailgun(mail)` and `client.send_message('my-domain', message_payload)`, so adding the following to my Gemfile works:

```ruby
gem 'mailgun-ruby', '~>1.1.4', require: ['mailgun', 'railgun/attachment', 'railgun/errors', 'railgun/mailer', 'railgun/message']
```

Do you have any thoughts on why this might be happening?

For development, my initializer is effectively this:

```ruby
# config/initializers/action_mailer.rb
Rails.application.config.action_mailer.default_url_options = { host: 'localhost', :port: 3000, protocol: 'http' }
Rails.application.config.action_mailer.asset_host = 'http://localhost:3000'
Rails.application.config.action_mailer.delivery_method = :smtp
Rails.application.config.action_mailer.smtp_settings = {
  address: 'smtp.mailgun.org',
  port: 587,
  domain: 'my-domain',
  user_name: 'username',
  password: 'supersecret',
  authentication: 'plain',
  enable_starttls_auto: true,
}
Rails.application.config.action_mailer.perform_deliveries = false
```

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Closes #86

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
This has failed CI on 2.2.10 and 2.3.7, but passed on the other 3 ruby versions (older and newer). This appears to be an issue with the CI/project setup and is unrelated to this PR:

> Could not find gem 'bundler (~> 1.16.2)' in any of the relevant sources:

**Comment by cgunther** [comment]
As a result of upgrading from Rails 5.2 to 6.0, I'm hitting a similar problem as #86 and I believe this fix is in the right direction, but not perfect yet.

Rails 6.0 deprecates the old jobs used to send emails in the background in favor of a new job (`ActionMailer::MailDeliveryJob`). The `new_framework_defaults_6_0.rb` initializer file has a line for you to uncomment to opt into the new job once you're stable on 6.0, however uncommenting it doesn't have the intended effect of using the new job.

The issue is that the initializer file sets the new job via `Rails.application.config.action_mailer`, and when `ActionMailer::Base` is loaded, the config you've set is copied to `ActionMailer::Base`. This gem currently eagerly loads `ActionMailer::Base` before configuration (and thus before initializers) as a result of adding the delivery method:
https://github.com/mailgun/mailgun-ruby/blob/f0f267a7900a183c62b97a833a792d65625febf4/lib/railgun/railtie.rb#L5-L7

That means the config is already copied from `Rails.application.config.action_mailer` to `ActionMailer::Base` before the initializer file is run to set the delivery job, thus yielding no effect.

Using `ActiveSupport.on_load(:action_mailer)` as this PR does is better so we don't force eagerly loading `ActionMailer::Base`, however I believe the initializer in this PR ends up running after the initializer defined by ActionMailer:
https://github.com/rails/rails/blob/464a86f90ba89ac97aac48e4191fffc8309c445f/actionmailer/lib/action_mailer/railtie.rb#L17

Which copies your config to `ActionMailer::Base`:
https://github.com/rails/rails/blob/464a86f90ba89ac97aac48e4191fffc8309c445f/actionmailer/lib/action_mailer/railtie.rb#L53

Which errors when it gets to `Rails.application.config.action_mailer.mailgun_settings` since there is no `ActionMailer::Base.mailgun_settings=` method (yet). The initializer defined in this PR would be run later, adding the delivery method, thus defining the `ActionMailer::Base.mailgun_settings=` method.

To fix this, I believe this gem's initializer needs to run before the one provided by ActionMailer so that we can add the delivery method before we try copying the `mailgun_settings`. I believe this can be achieved by changing the initializer line as follows:
```ruby
initializer "railgun.configure_rails_initialization", before: 'action_mailer.set_configs' do
```

Separately, I'm not sure where this line is coming from, perhaps something for your own application code?
```ruby
ActiveSupport.run_load_hooks(:mailgun_mailer, Railgun::Mailer)
```

**Comment by obahareth** [comment]
@cgunther @Benjamin-Dobell Any idea when this might be merged guys? Thanks!

**Comment by cgunther** [comment]
I'm just a fellow user of this library, so I have no control over merging. I stumbled onto the original fix and provided my feedback on how it worked for me.

**Comment by javierav** [comment]
Three hours of my life wasted until I found that the fault was in this gem! 🤯 And the problem was detected in February 2019 and still, almost two years later, it has not been fixed! 🤬  Bye bye Mailgun...

**Comment by javierav** [comment]
For future reference, the error that I was getting is:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.
```

Related with rails/rails#36546

**Comment by donrestarone** [comment]
Any updates on if this change will be merged? Its Feb 2021 and this is still an issue.

**Comment by subdigital** [comment]
The lack of response on this thread is concerning. Any updates from mailgun on when we can expect this to be resolved?

**Comment by Benjamin-Dobell** [comment]
How Not to Do Open Source 101, which your lecturer Mailgun: https://github.com/mailgun/mailgun-ruby/pull/227

**Pull request closed without merging**
