### PR TITLE
Fix for duplicate reply-to headers

### PR DESCRIPTION
**Pull request by giedomak**
There is a bug in `Railgun` where `build_message_object` would add the `h:reply-to` header, and where `transform_for_mailgun` would also add the `h:Reply-To` header.

This commit makes sure that `transform_for_mailgun` does not add the `h:Reply-To` header again, and this commit changes `reply_to=` in `MessageBuilder` to use the capitalized header (`h:Reply-To`).

### CODE REVIEW

**Comment by giedomak** [comment]
@pirogoeth If you will, could you please take a look into this PR and review it?

**Comment by johnrees** [comment]
I just came across this bug, is it possible to get it merged? Or is there a quick hotfix for it in the meantime? Thanks!

**Comment by giedomak** [comment]
Paging @pirogoeth again.

@johnrees, we switched away from using `reply-to` all together, we're now using the `Sender` and `From` headers.

**Comment by joshm1204** [comment]
How is `reply-to` different from `Sender` and `From`? 

I see the bug and since `reply-to` is still usable, I think it should be fixed.

**Comment by giedomak** [comment]
This seems like a reasonable explanation: 

> The `Sender` header is used to identify in the message who submitted it. This is usually the same as the `From` header, which is who the message is from. However, it can differ in some cases where a mail agent is sending messages on behalf of someone else.

https://stackoverflow.com/questions/4367358/whats-the-difference-between-sender-from-and-return-path

**Comment by joshm1204** [comment]
Has the duplicate reply-to headers issue been resolved yet? Will this be merged? Was it merged?

**Comment by joshm1204** [comment]
I see this issue was closed without comment.  Was the issue fixed? Even if you use from and sender, reply-to is still a duplcate.

**Comment by giedomak** [comment]
I've submitted this PR on 8 Nov 2018. Maybe you have better luck trying to get something merged here...

**Pull request closed without merging**
