### PR TITLE
bump to version 1.1.0

### PR DESCRIPTION
**Pull request by jrodom**

### CODE REVIEW

**Comment by gimpporbust** [comment]
Can I make a suggestion to bump to version `3.0.0`? Unless the different versions of the Mailgun api are backwards compatible. I see that #49 was just merged meaning we're now using `v3` of the api, so if there are any breaking changes from how `v2` was used going to `v3` there should be a major version increment. Then we will also have the benefit of pairing the Mailgun api version with the gem major version, which is nice.

Just a thought.

**Comment by dan-ding** [comment]
@gimpporbust "If you’re currently using /v2/<domain>/bounces API to poll for most recently occurred bounces, you can continue using it but do not rely on total_count." -- http://blog.mailgun.com/default-api-version-now-v3/

Otherwise things should be backwards compatible.

**Comment by lukebooth** [comment]
This or #51 should be merged. New people using the gem are getting confused that v1.0.5 doesn't exist.

**Comment by pirogoeth** [comment]
This will be taken care of today :)

**Pull request closed without merging**
